name: nop_flutter
description: 依赖注入，状态管理
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  nop:
    git:
      url: https://github.com/sersr/nop.git

dependency_overrides:
  nop: 
    path: ../nop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0